global:
  email-reply-to: rodriguez.jorge@salesforce.com
  email-only-last-committer-on-dev-branch: false
  parameters:
    - name: "JAVA_VERSION"
      default: "onejdk17"
      description: "Java version to be used"
      type: "choice"
      choices:
        - onejdk8_basic
        - onejdk11
        - onejdk17
        - onejdk21
      required: true
    - name: "MAVEN_VERSION"
      default: "MVN-3.9.4"
      description: "Maven version to be used"
      type: "choice"
      choices:
        - MVN-3.8.8
        - MVN-3.9.0
        - MVN-3.9.4
        - MVN-3.9.6
        - MVN-3.9.9
      required: true
    - name: "VERSION"
      type: "string"
      description: "Version used in the release"
    - name: "RELEASE_AS_RC"
      default: "false"
      description: "Indicates if the deploy will be a release candidate"
      type: "boolean"
  production-branches:
    - main
stages:
  build:
    - step:
        name: configure-workspace
        image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_rhel9_java_build/java11
        commands:
          - chmod +x setup.sh
          - ./setup.sh -s settings.xml
    - step:
        name: build-artifacts
        image: docker.repo.local.sfdc.net/sfci/onejdk/salesforcejdk/sfdc_rhel9_$$PARAMETERS_JAVA_VERSION
        environment:
          - name: PARAMETERS_MAVEN_VERSION
        commands:
          - ./setup.sh -m $PARAMETERS_MAVEN_VERSION
          - mvn clean install test -DskipTests -Dmaven.test.skip=true
