global:
  email-reply-to: rodriguez.jorge@salesforce.com
  email-only-last-committer-on-dev-branch: false
  log-level: debug
  parameters:
    - name: "JAVA_VERSION"
      default: "onejdk17"
      description: "Java version to be used"
      type: "choice"
      choices:
        - onejdk8_basic
        - onejdk11
        - onejdk17
        - onejdk21
      required: true
    - name: "MAVEN_VERSION"
      default: "MVN-3.9.4"
      description: "Maven version to be used"
      type: "choice"
      choices:
        - MVN-3.8.8
        - MVN-3.9.0
        - MVN-3.9.4
        - MVN-3.9.6
        - MVN-3.9.9
      required: true
    - name: "VERSION"
      type: "string"
      description: "Version used in the release"
    - name: "RELEASE_AS_RC"
      default: "false"
      description: "Indicates if the deploy will be a release candidate"
      type: "boolean"
  production-branches:
    - main
    - tasks/poc-sfci-v8
stages:
  precheck:
    # Take the Maven settings and add the required repositories and servers in the following steps.
    - step:
        name: configure-workspace
        image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_rhel9_java_build/java11
        environment:
          - name: M2_SETTINGS
            value: $$m2_settings
        commands:
          - chmod +x setup.sh
          - ./setup.sh -s settings.xml "/cix/tmp/.strata/.m2/repository"
          - cp settings.xml $M2_SETTINGS
          - mvn org.apache.maven.plugins:maven-help-plugin:3.5.1:effective-settings
  build:
    # Performs the build and execution of the unit-tests
    - step:
        name: build-artifacts
        image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_rhel9_java_build:latest
        environment:
          - name: PARAMETERS_MAVEN_VERSION
        commands:
          - mvn clean install -DskipTests
    - snyk-scan:
        snyk-scan-detection-depth: 4 # This is to avoid scan the pom.xml in the tests
  publish:
    - publish-jar:
        artifacts:
          - groupId: "org.mule.tools.maven"
            artifactId: "mule-extension-model-loader"
          - groupId: "org.mule.tools.maven"
            artifactId: "mule-classloader-model"
          - groupId: "org.mule.tools.maven"
            artifactId: "mule-deployer"
          - groupId: "org.mule.tools.maven"
            artifactId: "mule-packager"
          - groupId: "org.mule.tools.maven"
            artifactId:  "mule-maven-plugin"
