global:
  email-reply-to: rodriguez.jorge@salesforce.com
  email-only-last-committer-on-dev-branch: false
  parameters:
    - name: "JAVA_VERSION"
      default: "JDK-17"
      description: "Java version to be used"
      type: "choice"
      choices:
        - JDK-1.8
        - JDK-11
        - JDK-17
        - JDK-21
      required: true
    - name: "MAVEN_VERSION"
      default: "MVN-3.9.4"
      description: "Maven version to be used"
      type: "choice"
      choices:
        - MVN-3.8.8
        - MVN-3.9.0
        - MVN-3.9.4
        - MVN-3.9.8
        - MVN-3.9.9
      required: true
    - name: "VERSION"
      type: "string"
      description: "Version used in the release"
    - name: "RELEASE_AS_RC"
      default: "false"
      description: "Indicates if the deploy will be a release candidate"
      type: "boolean"
  production-branches:
    - main
stages:
  build:
    - step:
        name: configure-workspace
        image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_rhel9_java_build/java11
        commands:
          - chmod +x setup.sh && ./setup.sh -s settings.xml
    - step:
        name: build-artifacts-java-1.8
        image: docker.repo.local.sfdc.net/sfci/onejdk/salesforcejdk/sfdc_rhel9_onejdk8_basic
        environment:
          - name: PARAMETERS_JAVA_VERSION
          - name: PARAMETERS_MAVEN_VERSION
        commands:
          - ./setup.sh e
        when:
          - operator: EQ
            value: $$PARAMETERS_JAVA_VERSION
            other: "JDK-1.8"
    - step:
        name: build-artifacts-java-11
        image: docker.repo.local.sfdc.net/sfci/onejdk/salesforcejdk/sfdc_rhel9_onejdk11
        environment:
          - name: PARAMETERS_JAVA_VERSION
          - name: PARAMETERS_MAVEN_VERSION
        commands:
          - ./setup.sh e
        when:
          - operator: EQ
            value: $$PARAMETERS_JAVA_VERSION
            other: "JDK-11"
    - step:
        name: build-artifacts-java-17
        image: docker.repo.local.sfdc.net/sfci/onejdk/salesforcejdk/sfdc_rhel9_onejdk17
        environment:
          - name: PARAMETERS_JAVA_VERSION
          - name: PARAMETERS_MAVEN_VERSION
        commands:
          - ./setup.sh e
        when:
          - operator: EQ
            value: $$PARAMETERS_JAVA_VERSION
            other: "JDK-17"
    - step:
        name: build-artifacts-java-21
        image: docker.repo.local.sfdc.net/sfci/onejdk/salesforcejdk/sfdc_rhel9_onejdk21
        environment:
          - name: PARAMETERS_JAVA_VERSION
          - name: PARAMETERS_MAVEN_VERSION
        commands:
          - ./setup.sh e
        when:
          - operator: EQ
            value: $$PARAMETERS_JAVA_VERSION
            other: "JDK-21"
